### ISSUE TITLE
How to link the frame and the window of DIA-PASEF?

### ISSUE THREAD

**Issue by hcji** [MatteoLacki/timspy#3]
Hi, 

I m trying to parse a .d file of a DIA-PASEF mode with your package by:

    tims = 'd:/data/293T_200ng_DIA_28fixed_timscontrol_25Da_Slot1-15_1_386.d'  
    D = TimsDIA(tims)  
    frames = D.frames  
    windows = D.windows  
    
    frames.columns
    Index(['rt', 'Polarity', 'ScanMode', 'MsMsType', 'TimsId', 'MaxIntensity',
       'SummedIntensities', 'NumScans', 'NumPeaks', 'MzCalibration', 'T1',
       'T2', 'TimsCalibration', 'PropertyGroup', 'AccumulationTime',
       'RampTime'],
      dtype='object')

    windows.columns
    Index(['scan_min', 'scan_max', 'mz_left', 'mz_right', 'win', 'stripe', 'left',
       'right', 'prev_left', 'prev_right', 'IM_min', 'IM_max'],
      dtype='object')

It seems the frames object contains the information of a frame, and windows object describes the window of a PASEF scan. But how can I know which window is corresponding a specific frame?

**Comment by MatteoLacki** [comment]
I will implement this function today later on and add it to the package.
The windows are in consecutive order: they follow a scheme described in the
diaPASEF papers.


*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by MatteoLacki** [comment]
Hi,

Open your data with
```python
from timspy.df import TimsPyDIA

D = TimsPyDIA("path_to_your_d_folder")
D.frames_meta()

#           Id         Time Polarity  ScanMode  MsMsType     TimsId  \
# 0          1     0.326492        +         9         0          0   
# 1          2     0.434706        +         9         9       8192   
# ...      ...          ...      ...       ...       ...        ...   
# 11551  11552  1243.811222        +         9         9  995631104   
# 11552  11553  1243.919337        +         9         9  995635200   

#        MaxIntensity  SummedIntensities  NumScans  NumPeaks  MzCalibration  \
# 0               192              95955       918      1601              1   
# 1              2384             579402       918      6598              1   
# ...             ...                ...       ...       ...            ...   
# 11551           167               8097       918       360              1   
# 11552           155               8633       918       397              1   

#               T1         T2  TimsCalibration  PropertyGroup  AccumulationTime  \
# 0      25.570898  26.677390                1              1            99.953   
# 1      25.570898  26.677390                1              1            99.953   
# ...          ...        ...              ...            ...               ...   
# 11551  25.571281  26.633296                1              1            99.953   
# 11552  25.571281  26.633296                1              1            99.953   

#        RampTime  Windows_idx  WindowGroup  ScanNumBegin  ScanNumEnd  \
# 0        99.953          NaN          NaN           NaN         NaN   
# 1        99.953          0.0          1.0           0.0        36.0   
# ...         ...          ...          ...           ...         ...   
# 11551    99.953        504.0         21.0         147.0       183.0   
# 11552    99.953        505.0         21.0         184.0       220.0   

#        IsolationMz  IsolationWidth  CollisionEnergy      mz_left     mz_right  
# 0              NaN             NaN              NaN          NaN          NaN  
# 1      1283.384615            36.0             10.0  1265.384615  1301.384615  
# ...            ...             ...              ...          ...          ...  
# 11551  1343.897436            36.0             10.0  1325.897436  1361.897436  
# 11552  1299.025641            36.0             10.0  1281.025641  1317.025641  

# [11553 rows x 26 columns]

```

**Comment by hcji** [comment]
> Hi,
> 
> Open your data with
> 
> ```python
> from timspy.df import TimsPyDIA
> 
> D = TimsPyDIA("path_to_your_d_folder")
> D.frames_meta()
> 
> #           Id         Time Polarity  ScanMode  MsMsType     TimsId  \
> # 0          1     0.326492        +         9         0          0   
> # 1          2     0.434706        +         9         9       8192   
> # ...      ...          ...      ...       ...       ...        ...   
> # 11551  11552  1243.811222        +         9         9  995631104   
> # 11552  11553  1243.919337        +         9         9  995635200   
> 
> #        MaxIntensity  SummedIntensities  NumScans  NumPeaks  MzCalibration  \
> # 0               192              95955       918      1601              1   
> # 1              2384             579402       918      6598              1   
> # ...             ...                ...       ...       ...            ...   
> # 11551           167               8097       918       360              1   
> # 11552           155               8633       918       397              1   
> 
> #               T1         T2  TimsCalibration  PropertyGroup  AccumulationTime  \
> # 0      25.570898  26.677390                1              1            99.953   
> # 1      25.570898  26.677390                1              1            99.953   
> # ...          ...        ...              ...            ...               ...   
> # 11551  25.571281  26.633296                1              1            99.953   
> # 11552  25.571281  26.633296                1              1            99.953   
> 
> #        RampTime  Windows_idx  WindowGroup  ScanNumBegin  ScanNumEnd  \
> # 0        99.953          NaN          NaN           NaN         NaN   
> # 1        99.953          0.0          1.0           0.0        36.0   
> # ...         ...          ...          ...           ...         ...   
> # 11551    99.953        504.0         21.0         147.0       183.0   
> # 11552    99.953        505.0         21.0         184.0       220.0   
> 
> #        IsolationMz  IsolationWidth  CollisionEnergy      mz_left     mz_right  
> # 0              NaN             NaN              NaN          NaN          NaN  
> # 1      1283.384615            36.0             10.0  1265.384615  1301.384615  
> # ...            ...             ...              ...          ...          ...  
> # 11551  1343.897436            36.0             10.0  1325.897436  1361.897436  
> # 11552  1299.025641            36.0             10.0  1281.025641  1317.025641  
> 
> # [11553 rows x 26 columns]
> ```

Thanks for your reply.
